### ISSUE TITLE
How do I use agree-score and disagree?

### ISSUE THREAD

**Issue by wang9702** [sajith-rahim/fs-em#1]
Thank you for sharing this excellent project. What is the purpose of the agreed -score and disagree?

**Comment by sajith-rahim** [comment]
We use `w = log2[m/u]` as comparison weight for each column mapping in the Fellegi Sunter model.

Refer:
https://courses.cs.washington.edu/courses/cse590q/04au/papers/Felligi69.pdf
https://courses.cs.washington.edu/courses/cse590q/04au/papers/WinklerEM.pdf
